source: widowx_arm.yaml
port: /dev/ttyUSB0
read_rate: 50
write_rate: 50

joints: {
    joint_1: {id: 1, ticks: 4096, range: 360.0, max_speed: 500.0},
    joint_2: {id: 2, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 400.0},
    joint_3: {id: 3, ticks: 4096, range: 360.0, max_speed: 400.0, invert: true},
    joint_4: {id: 4, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 700.0, invert: true},
}
controllers: {
    arm_controller: {type: follow_controller, joints: [joint_1, joint_2, joint_3, joint_4], action_name: arm_controller/follow_joint_trajectory, onboard: False },
}