port: /dev/ttyUSB0

# arbotix specific config params
source: widowx_arm.yaml
read_rate: 50
write_rate: 50

# joint params
joints: {
    joint_1: {id: 1,
              ticks: 4096,                     # number of positions in the servo (not currently used for u2d2)
              range: 360.0,                    # range of the servo (not currently used for u2d2)
              min_angle: -180.0,               # minimum angle (position) for the servo (in degrees)
              max_angle: 180.0,                # maximum angle (position) for the servo (in degrees)
              max_speed: 14,                   # maximum speed (velocity) for the servo (in deg/sec)
              max_accel: 100,                  # maximum acceleration for the servo (in deg/sec^2)
              torque_off_safe_position: 0.0,   # position (radians) of a safe position to hold the joint before disabling torques
              type: MX28                       # type of servo (either MX28 or MX64)
    },
    joint_2: {id: 2,
              ticks: 4096,
              range: 360.0,
              min_angle: -90.0,
              max_angle: 90.0,
              max_speed: 14,
              max_accel: 100,
              torque_off_safe_position: -1.65,
              type: MX64
    },
    joint_3: {id: 3,
              ticks: 4096,
              range: 360.0,
              min_angle: -90.0,
              max_angle: 90.0,
              max_speed: 14,
              max_accel: 100,
              torque_off_safe_position: -1.65,
              type: MX64,
              invert: true                    # arbotix-specific param
    },
    joint_4: {id: 4,
              ticks: 4096,
              range: 360.0,
              min_angle: -90.0,
              max_angle: 90.0,
              max_speed: 14,
              max_accel: 100,
              torque_off_safe_position: 0.0,
              type: MX28,
              invert: true
    },
}
# controllers
controllers: {
    arm_controller: {
        type: follow_controller,
        joints: [joint_1, joint_2, joint_3, joint_4],
        action_name: arm_controller/follow_joint_trajectory,
        onboard: False
    }
}
